name: Import XML Feed to Supabase
permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:  # Možnosť manuálneho spustenia
  schedule:
    - cron: "0 0,6,12,18 * * *"  # Automatické spustenie každých 6 hodín

jobs:
  import_feed:
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Checkout repo
        uses: actions/checkout@v4

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 📦 Install dependencies
        run: |
          npm install dotenv
          npm install

      - name: 🚀 Run product import script in a loop for 6 hours
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          echo "🚀 Starting continuous import loop..."
          end=$((SECONDS+21600))  # 21600 sekúnd = 6 hodín
          while [ $SECONDS -lt $end ]; do
            echo "🔄 Running product import at $(date)"
            node importXMLFeed.js 2>&1 | tee -a import_log.txt
            sleep 20  
          done
          echo "✅ Completed 6-hour import cycle."

      - name: 🚀 Commit & Push updated XML feed
        run: |
          echo "🔄 Checking for XML changes..."
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add feed.xml
          git diff --cached --exit-code || (git commit -m "🔄 Auto-update XML feed" && git push origin main)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🛑 Allow Manual Workflow Cancellation
        if: always()
        run: |
          echo "🔴 Workflow can be manually canceled if needed."
      
      - name: 📜 Upload log on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: import-log
          path: import_log.txt
